name: Changelog generator
on:
  release:
    types:
      - created
jobs:
  changelog:
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3.1.0
      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.MD
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update Changelog
          file_pattern: "CHANGELOG.MD"
          branch: 1.19.2-dev
          repository: .
